README.md
configs/nginx.conf
configs/nginx_ssl.conf
configs/www-pterodactyl.conf
install-daemon.sh
install-panel.sh

Implement support for CentOS 7, 8 on panel and daemon installations. Still work in progress, not ready for merging.
Fixes #11

[WIP] CentOS 7, 8 support for panel and daemon

---

install-panel.sh

It gives an error if it's not started !

Launch MySQL Server before entering credentials

---

install-daemon.sh

Updates to go along with the Zorin updates for the panel.

Add support for Zorin OS (daemon)

---

install-panel.sh

Obfuscate MySQL password input

---

README.md
install-daemon.sh
install-panel.sh

- Optional: setup Let's Encrypt SSL automatically
- Optional: configure UFW.
- Suggest to the user: install the daemon on the same machine.
Thanks to @MrFlacko for the initial work of this.

Let's Encrypt SSL, UFW and suggested daemon install.

---

configs/pterosftp.service
install-daemon.sh

daemon: Option to install the standalone SFTP server

---

install-daemon.sh

Not yet tested, will do some testing before it is ready for merge.
Fixes #23

daemon: Option to install MariaDB (MySQL) server

---

install-daemon.sh

panel: Remove redundant "sudo" reference (Debian)

---

install-daemon.sh

I added **architecture checking**, **virtualization type checking** and **checking for unsupported kernel parameters (xxxx)**. (Check out the code for any spelling mistakes).

 More compatibility checks

---

install-panel.sh
install-wings.sh

Kinda tested (not fully) on ubuntu and centOS VMs. Again check for typos,I have changed code editor, indentations now should be normal. Also at one point there was a big problem for me with CRLF and LF (commits where kinda overwritten, but after a merging an older commit it seems to be fixed).
Fixes #41

Added Firewall-cmd support for panel and firewall support for daemon

---

install-panel.sh

Issue #61 fix. Thinking about adding more functionality :)

Adding support to bypass letsencrypt after failing it

---

install-panel.sh

panel: remove TLSv1.3 ssl_protocol in nginx config on debian 8/9

---

README.md
install-daemon.sh
install-panel.sh

Implement support for Ubuntu 20.04 on panel/daemon. #52 already has this but I decided to backwards implement it.

Implement Ubuntu 20 support

---

install-wings.sh

Automatic Let's Encrypt for daemon (wings)

---

README.md

Duplicate of #107 but I messed it up (did `git checkout` with my other PR as the base and not `master`, rookie mistake...).

Use own domain as script entrypoint

---

README.md

Remove unnecessary firewall instructions from README

---

install-wings.sh

wings: Minor misspelling and rephrase warning

---

install-wings.sh

panel: fix broken if statement in perform_install function

---

install-panel.sh

panel: force composer install

---

install-panel.sh
lib/verify-fqdn.sh

Verifies that the FQDN provided by user is valid.

Add a way to verify that a FQDN is valid

---

install-panel.sh
install-wings.sh
install.sh
legacy/daemon_0.6.sh
legacy/panel_0.7.sh
lib/verify-fqdn.sh

Update all copyright notices to 2021

---

install-panel.sh

panel: remove ability to run p:environment:mail, redundant

---

install-panel.sh

panel: add option to generate MySQL password automatically

---

install-wings.sh

wings: let's encrypt now checks with verify-fqdn before accepting cert

---

install-panel.sh

panel: --settings-ui=true, not --settings-ui=yes

---

install-panel.sh
install-wings.sh

* panel: remove deprecated third-party addons
* panel: not show port warning when CONFIGURE_FIREWALL is true
* wings: not show port warning when CONFIGURE_FIREWALL is true
* wings: add instructions on how to use auto-deploy
fixes #129

wings: add instructions on how to use auto deploy feature

---

install-panel.sh

Add OS architecture checking. Exactly the same as in wings.
Fixes #158

panel: Check OS architecture

---

install-wings.sh

wings: allow to override virt-what check

---

install-panel.sh
install-wings.sh

Added email validation with regex. I think it works great, as far as I tested.
Fixes #157

panel/wings: Add email validation

---

install-wings.sh

wings: Automatically skip MariaDB question if MySQL/MariaDB is detected

---

install-wings.sh

Support installing Wings on arm64

---

README.md
Vagrantfile
install-panel.sh
install-wings.sh
install.sh

Adds Debian 11 support
Fixes #230
I think I changed everything, but if I missed something please tell.
Tested on Debian 11 vagrant (didn't test with let's encrypt)

Add debian 11 support

---

install-panel.sh
install-wings.sh

This pull request adds the automatic configuration of database hosts to the script.
It will ask you for the username and password of the database user and then create the user.
Fixes #220

Database hosts

---

install-panel.sh

panel: use mysql_secure_installation on CentOS 8

---

install-wings.sh

wings: make sure epel-release is installed before certbot

---

install.sh

Changes how `install.sh` works (instead of functions variables) and adds logging functionality.
Fixes #249

Add script logging

---

install.sh

This fixes a typo with the pipe (`>` is now `>>`)
Fixes #254

Append to log instead of overwriting it with the header

---

install-panel.sh
install-wings.sh

panel/wings: disallow hyphens for database name/usernames

---

configs/nginx.conf
configs/nginx_ssl.conf

panel: Add listen [::]:80 and listen [::]:443 to nginx configs

---

README.md
install-panel.sh
install-wings.sh
install.sh
legacy/daemon_0.6.sh
legacy/panel_0.7.sh
lib/verify-fqdn.sh

Update copyright year to 2022

---

README.md
install-wings.sh

Replace references to daemon with Wings

---

install-wings.sh

Fixes #267 
Also adds restarting of `mysqld` to apply config changes.

Fix database hosts

---

install-wings.sh

wings: Avoid usage of apt-key.

---

README.md

**This is not intended as PR Spam, feel free to change the README by your own.**

Add a * to Debian 8

---

README.md
Vagrantfile
install-panel.sh
install-wings.sh

Support for Ubuntu 22.04

---

install-panel.sh

Just change out `wget` in favor of `curl`.
Fixes #337

Use curl instead of wget

---

uninstall.sh

compatibility to ubuntu 22.04, I have checked the compatibility by modifying the raw and it has worked perfectly in ubuntu 22.04
compatibility to ubuntu 22.04
Fixes #??
compatibility to ubuntu 22.04

update uninstall.sh, compatibility to ubuntu 22.04

---

install-panel.sh

php 8.1 version update
Fixes #php new version support for debian and ubuntu (php8.1) pterodactyl not have sup for old versions

panel: Update PHP version to 8.1

---

installers/panel.sh
lib/lib.sh
ui/uninstall.sh
ui/wings.sh

Fixes #365 and a few shellcheck issues.
Fixes `php-posix` missing from almalinux and rocky Linux scripts. (upstream changed)

Fix ask_database_external, shellcheck issues, alma and rocky

---

installers/panel.sh
installers/wings.sh

The wings script is calling a non-existing function.
Fixes #376

Fix wings script calling wrong firewall function

---

lib/lib.sh

Fixes #392
Fixes #385 
And OS checking, if OS is supported, but major version not.

Fix OS check, print_list and $PATH

---

.github/workflow_scripts/panel-install.sh
.github/workflow_scripts/wings-install.sh
README.md
install.sh
installers/panel.sh
installers/phpmyadmin.sh
installers/uninstall.sh
installers/wings.sh
lib/lib.sh
lib/verify-fqdn.sh
ui/panel.sh
ui/uninstall.sh
ui/wings.sh

Updated copyright year to 2024.

Update copyright year to 2024

---

configs/pteroq.service

added following options
StartLimitInterval=180
StartLimitBurst=30
RestartSec=5s
from official documentation https://pterodactyl.io/panel/1.0/getting_started.html#queue-listeners

configs/pteroq.service: update systemd unit file for pteroq

---

.github/workflows/wings.yml
README.md
Vagrantfile
lib/lib.sh

Add support for Ubuntu 24.04

---

README.md
install.sh
installers/uninstall.sh
installers/wings.sh

- Added checks before rm -rfing files
- Added extra logging when allowing ports in firewall

Made enhancements

---

README.md
installers/panel.sh

Updated PHP to 8.3 which is now used in the ptero docs

Update from php 8.1 to 8.3

---

.github/workflow_scripts/panel-install.sh
.github/workflow_scripts/wings-install.sh
README.md
install.sh
installers/panel.sh
installers/phpmyadmin.sh
installers/uninstall.sh
installers/wings.sh
lib/lib.sh
lib/verify-fqdn.sh
ui/panel.sh
ui/uninstall.sh
ui/wings.sh

Update copyright year to 2025
