pterodactyl-installer/pterodactyl-installer

- install-panel.sh
Easier for the user, avoids typing in the same password several times.
**Only works for non-CentOS installations.**
Fixes #19
> Perform MySQL queries without root password

- install-panel.sh
I was experimenting with Zorin as that's all I had laying around on a USB Stick at the time, as the OS is built on top of Ubuntu 18 there isn't much difference in the OS other than the overhauled UI. So I changed your script to include it locally. Just suggesting the change in case anyone else uses this. I was able to install and use it with those changes.
> Add support for Zorin OS (panel)

- install-daemon.sh
several people have reported that node-gyp is unable to install "mmmagic" due to some permission screw-up. See the linked issue.
this commit adds the "--unsafe-perm" parameter which tells npm to ignore the errors and proceed with install
Fixes #30
> Add "--unsafe-perm" parameter to "npm install"

- install-panel.sh
The package software-properties-common isn't installed before the command it provides (add-apt-repository) is ran.
The fix basically installs the necessary package. Though it is suggestion that this package is installed another way, or since the command 'apt install software-properties-common -y' is already within the script, that command should be ran before this script.
Though for now, this fixes the error message the start of running the script saying "Error: add-apt-repository. command not found"
Fixes #34
> Package not installed when function is ran

- install-panel.sh
Added a way to opt in to automatically setting up UFW
Added a way to opt in to automatically generating a HTTPS certificate
Added a way to opt in to running the daemon install script at the end
Removed some black Lines
Changed some wording in the script
Replaced some of the places for instead of typing 'yes' you do y/n with the default option capitalized.
This was tested on Ubuntu Server 18.04
I believe it should be set up to not interfere with any other version. 
The UFW is set to work on 16.04 as well, but the auto-cert doesn't run on 16.04, only 18.04
> Added Auto SSL, UFW and Suggested Daemon Install.

- install-panel.sh
When you choose ASSUME_SSL true, and LETSENCRYPT false the nginx will fail at the end of the script. This fixes that.
> Fixing nginx stopping the script

- legacy/daemon_0.6.sh
- legacy/panel_0.7.sh
These two new scripts download and modify the old versions of the script to install the 0.7.x version of the panel. Unsupported, will not get ANY bug fixes!
> panel/daemon: Add shorthand to old 0.7.x legacy scripts

- install-panel.sh
If the `setsebool` commands fail they will no longer cause the script to abort
Fixes #106
> panel: setsebool commands on CentOS can now fail without abort

- .gitignore
- README.md
- Vagrantfile
Testing the script manually means a lot of work. I've created a `Vagrantfile` so that the script can easily be tested on all supported installations. Simply run `vagrant up ubuntu_focal`  or `vagrant up centos_7` and then `vagrant ssh <name, e.g. ubuntu_focal>` and the script from your project folder (i.e. included with any modifications you are yet to have committed) will be located in `/vagrant` directory.
Still WIP.
> Use Vagrant for local testing/development

- install-wings.sh
Changed all 
```bash
"$var"
```
to 
```bash
[ "$var" == true ]
```
> wings: use bracket statements

- configs/pteroq.service
- install-panel.sh
Based on OS changes the user in `pteroq` service file.
Fixes #165
> panel: User based on OS pteroq

- README.md
- install-panel.sh
Use `php8.0` instead of `php7.4`. `PHP 8` is supported since panel `v1.3.0`
Everything should work as expected as it basically was find 7.4 and replace it with 8.0. (Mostly because `sury` repo includes `8.0`)
Tested on `Debian 10`
> panel: Use php8.0

- install-panel.sh
Fixed a critical bug if `configure_nginx` is run again and `ln` fails, because the file exists. I added the `-f` flag so it forces to remove the file, if it already exists.
fixes #186
> panel: fix `ln` bug if file exist

- lib/verify-fqdn.sh
While installing I noticed a typo, fixed!
"Ecnrypt" -> "Encrypt"
Fixes #193
> "Ecnrypt" -> "Encrypt" typo fixed

- lib/verify-fqdn.sh
Disclaimer: I have only tested this in an online bash shell, please check if it properly works.
This should fix the situation where a CNAME record is used to point to a domain that points to the proper IP address.
It does break when someone uses a domain that contains the IP address but does not point to the IP address, but I think that's an bigger edge case than using CNAME records.
I'm open for other suggestions 😃 
Fixes #201
> Allow CNAME DNS records

- install-wings.sh
Make so that the script checks for openvz or lxc anywhere in the `virt-what` output.
Fixes #200
> wings: Fix checking of virtualization

- install.sh
The setup option refers options five and six (legacy panel+wings and canary panel), this should be six and seven (canary panel and canary wings)
> Fix incorrectly labeled setup option

- install-panel.sh
Add's a regex check similar to email, to check if provided FQDN is an IP.
> [panel] Check if FQDN is an IP

- install-wings.sh
Always add export `/sbin:/usr/sbin` to `$PATH`.
> Fix virt-what not found

- .github/workflows/panel.yml
- .github/workflows/wings.yml
- README.md
- Vagrantfile
- installers/panel.sh
- installers/wings.sh
- lib/lib.sh
Adds Debian 12 to workflows,
Supports it in `lib.sh`
Removes Ubuntu 18.04
Adds a periodic run of the workflows
Fixes #416
> Add debian 12 support, remove Ubuntu 18.04

- configs/valid_timezones.txt
This pull request fixes an error during the installation process by renaming Europe/Kiev renamed to Europe/Kyiv as Europe/Kiev is not a valid PHP timezone.
> Europe/Kiev renamed to Europe/Kyiv
